// Use Bun to run this!
/// <reference types="bun-types" />

interface IArgs {
  package: string;
  path: string;
  project: string;
  short: string;
}

const template = (args: IArgs) =>
  `# THIS FILE IS GENERATED by scripts/generate-actions.ts

name: ${args.short}

on:
  push:
    branches:
      - main

jobs:
  ignore_build:
    name: Ignored Build Step
    runs-on: ubuntu-latest
    outputs:
      run_rest_jobs: \${{ steps.set_output.outputs.run_jobs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Check if new build is needed
        id: set_output
        run: bash scripts/ignore-build.bash ${args.package}

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    
    needs: [ ignore_build ]
    if: needs.ignore_build.outputs.run_rest_jobs == 'true'

    permissions:
      contents: read
      deployments: write

    env:
      TURBO_TOKEN: \${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: leomotors

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm turbo run --filter="${args.package}" build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: \${{ secrets.GITHUB_TOKEN }}
          projectName: ${args.project}
          directory: ${args.path}/build
`;

const projects = [
  {
    package: "resume.leomotors.net",
    path: "apps/resume",
    project: "resume-leomotors",
    short: "resume",
  },
  {
    package: "leomotors.me",
    path: "apps/www",
    project: "www-leomotors",
    short: "www",
  },
] satisfies IArgs[];

projects.map((project) =>
  Bun.write(`.github/workflows/pages.${project.short}.yml`, template(project))
);
